name: calling tekton pipeline

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_commentary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Webhook
      uses: distributhor/workflow-webhook@v3
      env:
        webhook_type: 'json-extended'
        webhook_url: "http://e1dd-185-189-25-166.ngrok.io"
