name: calling tekton pipeline

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_commentary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      name: checkout
    - name: run shell
      run: |
        ls
        pwd
    # Runs a single command using the runners shell
    - name: Webhook
      uses: distributhor/workflow-webhook@v3.0.5
      env:
        webhook_type: "json-extended"
        webhook_url: "https://webhook.site/c090e142-3de6-4689-9071-107b574f47d2"
        webhook_secret: "ABCD"
        verbose: "true"
